[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
hex = "0.4"
rand = "0.8"
regex = "1"
num-bigint = { version = "0.4.6", features = ["rand"] }
num-traits = "0.2"
sha2 = "0.10.8"

[dev-dependencies]
assert_matches = "1.5"
